export const CharacterTypes = {
    UPDATE_CHAR1_FN: "UPDATE_CHAR1_FN",
    UPDATE_CHAR1_LN: "UPDATE_CHAR1_LN",
    UPDATE_CHAR2_FN: "UPDATE_CHAR2_FN",
    UPDATE_CHAR2_LN: "UPDATE_CHAR2_LN",
    UPDATE_CHAR3_FN: "UPDATE_CHAR3_FN",
    UPDATE_CHAR3_LN: "UPDATE_CHAR3_LN",
    SUBMIT: "SUBMIT",
};
